name: Scrape hreflang from URL and Commit if Changes Detected

on:
  workflow_dispatch:  # Permite ejecutar manualmente
  schedule:
    - cron: "0 12 * * *"  # Corre diariamente a las 12:00 UTC

jobs:
  scrape_and_save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Necesario para que git diff funcione correctamente

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -q requests beautifulsoup4 pyyaml

    - name: Scrape hreflang and save to YAML
      run: python scrape_hreflang.py

    - name: Check for changes
      id: check_changes
      run: |
        set -e  # Asegura que el script falle en caso de error
        git add html/hreflang_links.yaml
        if git diff --cached --quiet; then
          echo "No changes detected"
          echo "has_changes=false" >> $GITHUB_ENV
        else
          echo "Changes detected"
          echo "has_changes=true" >> $GITHUB_ENV
        fi

    - name: Commit and push changes if there are any
      if: env.has_changes == 'true'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git commit -m "Update hreflang_links.yaml with latest scrape results"
        git push
