name: Scrape hreflang from URL and Commit if Changes Detected

on:
  workflow_dispatch:  # Allows manual execution
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00 UTC

jobs:
  scrape_and_save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1  # Fetch only the latest commit to speed up workflow

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --no-cache-dir requests beautifulsoup4 pyyaml

    - name: Scrape hreflang and save to YAML
      run: python scripts/scrape_hreflang.py  # Updated path

    - name: Check for changes
      id: check_changes
      run: |
        git add html/hreflang_links.yaml
        if [[ -z $(git status --porcelain) ]]; then
          echo "No changes detected."
          echo "has_changes=false" >> $GITHUB_ENV
        else
          echo "Changes detected."
          echo "has_changes=true" >> $GITHUB_ENV
        fi

    - name: Commit and push changes if needed
      if: env.has_changes == 'true'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git commit -m "Update hreflang_links.yaml with latest scrape results"
        git push
