name: Scrape and Save HTML from hreflang URLs

on:
  workflow_dispatch:  # Allows manual execution
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours

jobs:
  scrape_and_save_html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Ensures at least one previous commit for git diff

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -q requests pyyaml

    - name: Scrape URLs from hreflang_links.yaml and save HTML files
      run: |
        python scripts/scrape_and_save_html.py

    - name: Check for changes
      id: check_changes
      run: |
        git add html/
        if git diff --cached --quiet; then
          echo "No changes detected"
          echo "has_changes=false" >> $GITHUB_ENV
        else
          echo "Changes detected"
          echo "has_changes=true" >> $GITHUB_ENV
        fi
        
    - name: Commit and push changes if there are any
      if: env.has_changes == 'true'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git commit -m "Updated HTML files with latest scrape results" || exit 0
        git push
