name: Update JSON SHA

on:
  push:
    paths:
      - 'json/*.json'
  workflow_dispatch: # Allows manual execution

jobs:
  update_sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SHA JSON file
        run: |
          mkdir -p json
          echo "{" > json/json_sha.json
          first=true
          for file in json/*.json; do
            sha=$(git hash-object "$file")
            [ "$first" = true ] && first=false || echo "," >> json/json_sha.json
            echo "  \"$(basename "$file")\": \"$sha\"" >> json/json_sha.json
          done
          echo "}" >> json/json_sha.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add json/json_sha.json
          git diff --staged --quiet || (git commit -m "Update JSON SHA file" && git push)
